# Generated by Django 5.1.1 on 2024-09-27 15:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Indica que esta é a migração inicial para o app
    initial = True

    dependencies = [
        # Dependência do modelo de usuário configurável no settings
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Criação do modelo "Post"
        migrations.CreateModel(
            name="Post",
            fields=[
                # Campo ID com auto incremento
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                # Campo timestamp com valor padrão sendo o horário atual
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                # Campo de texto para o conteúdo do post
                ("content", models.TextField()),
                # Chave estrangeira para o usuário que criou o post
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                # Ordenação dos posts por timestamp em ordem decrescente
                "ordering": ["-timestamp"],
            },
        ),
        # Criação do modelo "Profile"
        migrations.CreateModel(
            name="Profile",
            fields=[
                # Campo ID com auto incremento
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                # Campo bio com valor padrão e limite de caracteres
                ("bio", models.CharField(default="Hola, twitter", max_length=100)),
                # Campo de imagem com valor padrão
                ("image", models.ImageField(default="default.png", upload_to="")),
                # Chave única para o usuário associado ao perfil
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        # Criação do modelo "Relationship"
        migrations.CreateModel(
            name="Relationship",
            fields=[
                # Campo ID com auto incremento
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                # Chave estrangeira para o usuário que inicia a relação
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                # Chave estrangeira para o usuário que é o alvo da relação
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
