# Generated by Django 5.1.1 on 2024-09-27 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Dependência da migração inicial do app "twitter"
        ("twitter", "0001_initial"),
        # Dependência do modelo de usuário configurável no settings
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Criação do modelo "Comment"
        migrations.CreateModel(
            name="Comment",
            fields=[
                # Campo ID com auto incremento
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                # Campo de texto para o conteúdo do comentário
                ("content", models.TextField()),
                # Campo timestamp com valor automático de data e hora de criação
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                # Chave estrangeira para o post ao qual o comentário pertence
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="twitter.post",
                    ),
                ),
                # Chave estrangeira para o usuário que fez o comentário
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                # Ordenação dos comentários por timestamp em ordem decrescente
                "ordering": ["-timestamp"],
            },
        ),
        # Criação do modelo "Like"
        migrations.CreateModel(
            name="Like",
            fields=[
                # Campo ID com auto incremento
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                # Campo timestamp com valor automático de data e hora de criação
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                # Chave estrangeira para o post ao qual o like pertence
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="twitter.post",
                    ),
                ),
                # Chave estrangeira para o usuário que deu o like
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                # Garante que um usuário possa dar like em um post apenas uma vez
                "unique_together": {("post", "user")},
            },
        ),
    ]
