# Generated by Django 5.1.1 on 2024-09-29 01:26

import project_twitter.twitter.models.profile  # Importa o módulo de perfil para usar o validador de imagem

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Dependência da migração anterior que altera o campo "post" no modelo "Like"
        ("twitter", "0003_post_likes_alter_like_post"),
    ]

    operations = [
        # Altera o campo "image" no modelo "Profile"
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_pics/default.png",  # Define a imagem padrão para perfis
                upload_to="profile_pics/",  # Define o diretório de upload para as imagens de perfil
                validators=[project_twitter.twitter.models.profile.validate_image]  # Adiciona um validador de imagem personalizado
            ),
        ),
    ]
